### ISSUE TITLE
[WICKET-7013] IndexOutOfBoundsException in InSessionPageStore

### ISSUE THREAD

**Issue by jira-importer** [jira-importer/jira-to-github-issues#157]
<p>sometimes this happens in our Log:</p>

<p>We use Tocmat 9 with Wicket 9. The logs started appearing after an upgrade to Wicket 9. User experience does not seem to be affected.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
   at java.util.LinkedList.checkPositionIndex(LinkedList.java:564) ~[?:?]
   at java.util.LinkedList.listIterator(LinkedList.java:871) ~[?:?]
   at java.util.AbstractList.listIterator(AbstractList.java:311) ~[?:?]
   at java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:238) ~[?:?]
   at org.apache.wicket.pageStore.InSessionPageStore$SessionData.remove(InSessionPageStore.java:219) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.pageStore.InSessionPageStore$SessionData.add(InSessionPageStore.java:205) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.pageStore.InSessionPageStore$CountLimitedData.add(InSessionPageStore.java:313) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.pageStore.InSessionPageStore.addPage(InSessionPageStore.java:127) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.pageStore.CachingPageStore.addPage(CachingPageStore.java:71) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.pageStore.RequestPageStore.detach(RequestPageStore.java:114) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.page.PageManager.detach(PageManager.java:91) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.Application$2.onDetach(Application.java:1582) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.request.cycle.RequestCycleListenerCollection$3.notify(RequestCycleListenerCollection.java:105) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.request.cycle.RequestCycleListenerCollection$3.notify(RequestCycleListenerCollection.java:101) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.util.listener.ListenerCollection$1.notify(ListenerCollection.java:121) ~[wicket-util-9.11.0.jar:9.11.0]
   at org.apache.wicket.util.listener.ListenerCollection.reversedNotify(ListenerCollection.java:145) ~[wicket-util-9.11.0.jar:9.11.0]
   at org.apache.wicket.util.listener.ListenerCollection.reversedNotifyIgnoringExceptions(ListenerCollection.java:114) ~[wicket-util-9.11.0.jar:9.11.0]
   at org.apache.wicket.request.cycle.RequestCycleListenerCollection.onDetach(RequestCycleListenerCollection.java:100) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.request.cycle.RequestCycle.onDetach(RequestCycle.java:670) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.request.cycle.RequestCycle.detach(RequestCycle.java:625) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:285) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.protocol.ws.AbstractUpgradeFilter.processRequestCycle(AbstractUpgradeFilter.java:67) ~[wicket-<span class="code-keyword">native</span>-websocket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:208) ~[wicket-core-9.11.0.jar:9.11.0]
   at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:307) ~[wicket-core-9.11.0.jar:9.11.0]
   at jdk.internal.reflect.GeneratedMethodAccessor370.invoke(Unknown Source) ~[?:?]
   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
   at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at javax.security.auth.Subject.doAsPrivileged(Subject.java:550) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.68]
   at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143) ~[catalina.jar:9.0.68]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:178) ~[spring-security-oauth2-client-5.7.3.jar:5.7.3]
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186) ~[spring-security-web-5.7.3.jar:5.7.3]
   at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.22.jar:5.3.22]
   at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.22.jar:5.3.22]
   at jdk.internal.reflect.GeneratedMethodAccessor370.invoke(Unknown Source) ~[?:?]
   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
   at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at javax.security.auth.Subject.doAsPrivileged(Subject.java:550) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.68]
   at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143) ~[catalina.jar:9.0.68]
   at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.22.jar:5.3.22]
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
   at jdk.internal.reflect.GeneratedMethodAccessor370.invoke(Unknown Source) ~[?:?]
   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
   at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at javax.security.auth.Subject.doAsPrivileged(Subject.java:550) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.68]
   at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143) ~[catalina.jar:9.0.68]
   at de.bayern.stmelf.common.web.UnitOfWorkFilter.doFilter(UnitOfWorkFilter.java:28) ~[lib-kompat-trunk-SNAPSHOT.jar:trunk-SNAPSHOT]
   at jdk.internal.reflect.GeneratedMethodAccessor370.invoke(Unknown Source) ~[?:?]
   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
   at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at javax.security.auth.Subject.doAsPrivileged(Subject.java:550) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.68]
   at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143) ~[catalina.jar:9.0.68]
   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.22.jar:5.3.22]
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
   at jdk.internal.reflect.GeneratedMethodAccessor370.invoke(Unknown Source) ~[?:?]
   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
   at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at javax.security.auth.Subject.doAsPrivileged(Subject.java:550) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.68]
   at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143) ~[catalina.jar:9.0.68]
   at de.bayern.basis.web.SessionHijackingFilter.doFilter(SessionHijackingFilter.java:80) ~[lib-wicket-trunk-SNAPSHOT.jar:trunk-SNAPSHOT]
   at jdk.internal.reflect.GeneratedMethodAccessor370.invoke(Unknown Source) ~[?:?]
   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
   at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at javax.security.auth.Subject.doAsPrivileged(Subject.java:550) ~[?:?]
   at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.68]
   at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) ~[catalina.jar:9.0.68]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[catalina.jar:9.0.68]
   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[catalina.jar:9.0.68]
   at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[catalina.jar:9.0.68]
   at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[catalina.jar:9.0.68]
   at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769) ~[catalina.jar:9.0.68]
   at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206) ~[catalina.jar:9.0.68]
   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[catalina.jar:9.0.68]
   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[catalina.jar:9.0.68]
   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[catalina.jar:9.0.68]
   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-coyote.jar:9.0.68]
   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:9.0.68]
   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-coyote.jar:9.0.68]
   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-coyote.jar:9.0.68]
   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.68]
   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.68]
   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.68]
   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.68]
   at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:829) ~[?:?]</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Johannes Renoth" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>, imported from: <a href="https://issues.apache.org/jira/browse/WICKET-7013" target="_blank">IndexOutOfBoundsException in InSessionPageStore</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Martin Tzvetanov Grigorov" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2023-05-04T18:38:36+00:00
<li><b>imported</b>: 2025-11-27
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=svenmeier">svenmeier</a>:</i>
<p>As Martin has commented on your PR, this can only happen if the container serializes the session while  request is still detaching. Maybe this happens because we flush earlier now in Wicket 9.x?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>:</i>
<p>what is peculiar that this appears clustered:</p>

<p><span class="image-wrap" style=""><img src="https://issues.apache.org/jira/secure/attachment/13051970/13051970_image-2022-11-08-22-26-46-296.png" style="border: 0px solid black" /></span></p>

<p>each occurence is 10 to 100 of occurences spaced a few seconds apart or even under a second apart. At first i suspected some AJAX Timer Behavior running because it was so regular.</p>

<p> </p>

<p>The last occurence</p>

<p><span class="image-wrap" style=""><img src="https://issues.apache.org/jira/secure/attachment/13051971/13051971_image-2022-11-08-22-29-01-725.png" style="border: 0px solid black" /></span></p>

<p><span class="image-wrap" style=""><img src="https://issues.apache.org/jira/secure/attachment/13051972/13051972_image-2022-11-08-22-29-21-875.png" style="border: 0px solid black" /></span></p>

<p>No complaints by any user so far (this is a staging environment so its only developers there testing stuff). The error never occured in Production.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=svenmeier">svenmeier</a>:</i>
<p>Disable the debugbar on your staging system and see whether that fixes it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>:</i>
<p>since we disabled the DebugBar 8 days ago the error has not occured, this is no guarantee that this is the cause though since we had periods of up to 2 weeks where the error has not occured even with DebugBar enabled. I will continue to monitor for some more weeks. Just wanted to let you know what the status is.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>:</i>
<p>This error seems to be caused by DebugBar, we still have no occurence of this error since we disabled the DebugBar</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>:</i>
<p>The error returned shortly after reactivating the DebugBar in the staging environment 2 Weeks ago. We are pretty sure this error is caused by the Debugbar. If i run into this error while developing i will try to Debug it but so far no luck.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>dr0ps opened a new pull request, #587:<br/>
URL: <a href="https://github.com/apache/wicket/pull/587" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/wicket/pull/587</a></p>

<p>   InSessionPageStore.SessionData#pages is a LinkedList. LinkedList is not thread-safe and keeps a rather complex state as it has to keep track of first and last element and the list size. The combination leads to some fragility. For instance, if multiple threads concurrently remove the same element, both operations will succeed (and remove the same element) but the individually stored list size will get reduced twice. In the case of Wicket-6966 and <a href="https://issues.apache.org/jira/browse/WICKET-7013" title="IndexOutOfBoundsException in InSessionPageStore" class="issue-link" data-issue-key="WICKET-7013"><del>WICKET-7013</del></a> this has happened. The exception message states that the current list size is -1. <br/>
   InSessionPageStore.SessionData#pages is only accessed in InSessionPageStore.SessionData itself and InSessionPageStore.CountLimitedData. Most accesses are in synchronized instance methods. Unfortunately InSessionPageStore.SessionData#writeObject(OutputStream) contains multiple accesses of the pages list without any synchronization. Therefore should serialization occur while e.G. new page instances are being created this might corrupt the state of the LinkedList. <br/>
   This merge request removes the last unsynchronized calls.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 125fe8ab96ce54565aaadaa3ba911b57439b85e1 in wicket's branch refs/heads/master from dr0ps<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=125fe8ab96" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=125fe8ab96</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-6966" title="IndexOutOfBounds in InSessionPageStore" class="issue-link" data-issue-key="WICKET-6966"><del>WICKET-6966</del></a>, <a href="https://issues.apache.org/jira/browse/WICKET-7013" title="IndexOutOfBoundsException in InSessionPageStore" class="issue-link" data-issue-key="WICKET-7013"><del>WICKET-7013</del></a>: prevent unsynchronized access to pages (#587)</p>

<ul>
	<li>Wicket-6966: prevent unsynchronized access to pages</li>
</ul>


<ul>
	<li>Added concurrency test case</li>
</ul>


<p>---------</p>

<p>Co-authored-by: dr0ps <dr0ps@users.noreply.github.com></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit bd13a77cbccdd37ff058225ea1d0c06e257c9bdf in wicket's branch refs/heads/wicket-9.x from dr0ps<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=bd13a77cbc" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=bd13a77cbc</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-6966" title="IndexOutOfBounds in InSessionPageStore" class="issue-link" data-issue-key="WICKET-6966"><del>WICKET-6966</del></a>, <a href="https://issues.apache.org/jira/browse/WICKET-7013" title="IndexOutOfBoundsException in InSessionPageStore" class="issue-link" data-issue-key="WICKET-7013"><del>WICKET-7013</del></a>: prevent unsynchronized access to pages (#587)</p>

<ul>
	<li>Wicket-6966: prevent unsynchronized access to pages</li>
</ul>


<ul>
	<li>Added concurrency test case</li>
</ul>


<p>---------</p>

<p>Co-authored-by: dr0ps <dr0ps@users.noreply.github.com><br/>
(cherry picked from commit 125fe8ab96ce54565aaadaa3ba911b57439b85e1)</p>
