### ISSUE TITLE
[WICKET-7005] ByteBuddy IllegalStateException: Cannot inject already loaded type

### ISSUE THREAD

**Issue by jira-importer** [jira-importer/jira-to-github-issues#165]
<p>Sometimes we get following exception in our application. It happens during our regression application tests running on parallel.</p>

<p>We're running Wicket 9.11.0 with byteBuddy enabled (-Dwicket.ioc.useByteBuddy=true) on Java 17. We applied a workaround by changing this spring component to extend a single interface instead of being sole class. When using cglib there was no issue.</p>

<p> </p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Caused by: java.lang.RuntimeException: error <span class="code-keyword">while</span> injecting object [[Page class = com.project.core.web.page.login.LoginPage, id = 1, render count = 0]] of type [com.project.core.web.page.login.LoginPage]
    at org.apache.wicket.injection.Injector.inject(Injector.java:122)
    at org.apache.wicket.spring.injection.annot.SpringComponentInjector.inject(SpringComponentInjector.java:124)
    at org.apache.wicket.spring.injection.annot.SpringComponentInjector.onInstantiation(SpringComponentInjector.java:130)
    at org.apache.wicket.application.ComponentInstantiationListenerCollection$1.notify(ComponentInstantiationListenerCollection.java:38)
    at org.apache.wicket.application.ComponentInstantiationListenerCollection$1.notify(ComponentInstantiationListenerCollection.java:34)
    at org.apache.wicket.util.listener.ListenerCollection.notify(ListenerCollection.java:81)
    at org.apache.wicket.application.ComponentInstantiationListenerCollection.onInstantiation(ComponentInstantiationListenerCollection.java:33)
    at org.apache.wicket.Component.<init>(Component.java:691)
    at org.apache.wicket.MarkupContainer.<init>(MarkupContainer.java:180)
    at org.apache.wicket.Page.<init>(Page.java:171)
    at org.apache.wicket.Page.<init>(Page.java:160)
    at org.apache.wicket.markup.html.WebPage.<init>(WebPage.java:99)
    at com.project.core.web.page.base.AbstractprojectPage.<init>(AbstractprojectPage.java:64)
    at com.project.core.web.page.base.AbstractprojectPage.<init>(AbstractprojectPage.java:54)
    at com.project.core.web.page.base.projectPageImpl.<init>(projectPageImpl.java:66)
    at com.project.core.web.page.base.projectSimplePage.<init>(projectSimplePage.java:17)
    at com.project.core.web.page.login.LoginPage.<init>(LoginPage.java:86)
    at com.project.core.web.page.login.LoginPage.<init>(LoginPage.java:78)
    ... 151 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not create type
    at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:170)
    at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
    at org.apache.wicket.proxy.bytebuddy.ByteBuddyProxyFactory.createOrGetProxyClass(ByteBuddyProxyFactory.java:105)
    at org.apache.wicket.proxy.bytebuddy.ByteBuddyProxyFactory.createProxy(ByteBuddyProxyFactory.java:75)
    at org.apache.wicket.proxy.LazyInitProxyFactory.createProxy(LazyInitProxyFactory.java:160)
    at org.apache.wicket.spring.injection.annot.AnnotProxyFieldValueFactory.getFieldValue(AnnotProxyFieldValueFactory.java:166)
    at org.apache.wicket.injection.Injector.inject(Injector.java:111)
    ... 168 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot inject already loaded type: <span class="code-keyword">class </span>com.project.core.web.page.base.WicketProxy_DoubleClickPreventionSupport
    at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:286)
    at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118)
    at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:241)
    at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:148)
    at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
    at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6166)
    at org.apache.wicket.proxy.bytebuddy.ByteBuddyProxyFactory.lambda$createOrGetProxyClass$0(ByteBuddyProxyFactory.java:119)
    at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
    ... 174 common frames omitted
    </pre>
</div></div>
<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Miroslav Silhavy" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=moerty">moerty</a>, imported from: <a href="https://issues.apache.org/jira/browse/WICKET-7005" target="_blank">ByteBuddy IllegalStateException: Cannot inject already loaded type</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Martin Tzvetanov Grigorov" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2023-02-22T08:34:18+00:00
<li><b>imported</b>: 2025-11-27
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=svenmeier">svenmeier</a>:</i>
<p>I was able to find this error message once only:</p>

<p>    <a href="https://stackoverflow.com/questions/42602622/redefine-static-methods-with-bytebuddy" class="external-link" target="_blank" rel="nofollow noopener">https://stackoverflow.com/questions/42602622/redefine-static-methods-with-bytebuddy</a></p>

<p>Since this is related to class (re)eloading, I think this is rather a question to the ByteBuddy developers - Rafael Winterhalter seems to be very active on StackOverflow, so I'd suggest asking there.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=moerty" class="user-hover" rel="moerty">moerty</a> Could you please share the source code of com.project.core.web.page.base.DoubleClickPreventionSupport ? Or a similar class that reproduces the problem.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>:</i>
<p>We have the same Problem, it occurs occasionally in all environments</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth" class="user-hover" rel="renoth">renoth</a> If it is easy for you to reproduce it in your app then you could try with newer version of ByteBuddy. Just add a dependencyManagement for it in your pom.xml</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=damien.hollis">damien.hollis</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov" class="user-hover" rel="mgrigorov">mgrigorov</a> - we have hit this issue again with another <tt>@SpringBean</tt> that references a class rather than interface. I don't think there is anything special about the class being imported but here is the original class that we had this issue with:</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> <span class="code-keyword">class </span>DefaultDoubleClickPreventionSupportImpl <span class="code-keyword">implements</span> DoubleClickPreventionSupport {

    @Autowired
    <span class="code-keyword">private</span> Environment environment;

    @Override
    <span class="code-keyword">public</span> void apply(@NotNull MarkupContainer markupContainer) {
<span class="code-keyword">if</span> (environment.isDoubleClickPreventionEnabled()) {
    doApply(markupContainer);
}
    }

    void doApply(@NotNull MarkupContainer markupContainer) {
DisableDoubleClickBehaviour.applyTo(markupContainer);
    }

    @Override
    <span class="code-keyword">public</span> void applyToNonForm(@NotNull AbstractLink component, @NotNull AjaxRequestAttributes attributes) {
<span class="code-comment">// UnimarketAjaxLinkDisableDoubleClickListener works only on forms, <span class="code-keyword">for</span> regular links use the channel
</span><span class="code-keyword">if</span> (environment.isDoubleClickPreventionEnabled() && component.findParent(Form.class) == <span class="code-keyword">null</span>) {
    <span class="code-comment">// The ajax call on client side will be discarded <span class="code-keyword">if</span> there is an active/running request on the same channel
</span>    <span class="code-comment">// The channel is unique <span class="code-keyword">for</span> each compoenent, so that we will not discard ajax event on the same page from different link
</span>    attributes.setChannel(<span class="code-keyword">new</span> AjaxChannel(<span class="code-quote">"blockingChannel"</span> + component.getMarkupId(), AjaxChannel.Type.ACTIVE));
}
    }
} </pre>
</div></div>
<p>Which is now not a problem because our <tt>@SpringBean</tt> now references <tt>DoubleClickPreventionSupport</tt> but making this change everywhere is a hassle.</p>

<p>This feels like some kind of race condition and I tend to agree it is probably in bytebuddy but there does not appear to be any outstanding issue on their issue tracker for this kind of thing.</p>

<p>Unfortunately we cannot reproduce this consistently, so it is difficult to tell whether a new bytebuddy will help or not (there is nothing in the bytebuddy release notes that indicates anything related to this issue has been fixed).</p>

<p> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p>If you inject interface then Wicket will use a JDK proxy. If you inject a class then Wicket will use ByteBuddy.</p>

<p>Since there is no demo application attached to this ticket we cannot help you to debug it and report a bug for ByteBuddy.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>:</i>
<p>we have created a Quickstart to reproduce the Problem with Bytebuddy</p>

<p>just run all tests in the attached quickstart</p>

<p>see <a href="https://issues.apache.org/jira/browse/WICKET-7005" title="ByteBuddy IllegalStateException: Cannot inject already loaded type" class="issue-link" data-issue-key="WICKET-7005"><del>WICKET-7005</del></a>.zip</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
[INFO] --- maven-surefire-plugin:2.12.4:test (<span class="code-keyword">default</span>-test) @ cb-afsb ---
[INFO] Surefire report directory: /home/martin/tmp/wicket/7005/target/surefire-reports
[INFO] [stdout] 
[INFO] [stdout] -------------------------------------------------------
[INFO] [stdout]  T E S T S
[INFO] [stdout] -------------------------------------------------------
[INFO] [stdout] Running TestSuite
[INFO] [stdout] Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@dfd3711
[INFO] [stdout] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.423 sec
[INFO] [stdout] 
[INFO] [stdout] Results :
[INFO] [stdout] 
[INFO] [stdout] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] [stdout] 
[INFO] Segment walltime 0 s, segment projects service time 0 s, effective/maximum degree of concurrency 1.00/7
 </pre>
</div></div>
<p>0 tests have ran.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=solomax">solomax</a>:</i>
<p>Reproducible for me <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: /opt/maven
Java version: 17.0.5, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: <span class="code-quote">"linux"</span>, version: <span class="code-quote">"5.19.0-32-<span class="code-keyword">generic</span>"</span>, arch: <span class="code-quote">"amd64"</span>, family: <span class="code-quote">"unix"</span>

Ubuntu 22.04.2 LTS
</pre>
</div></div>

<p>got</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: error <span class="code-keyword">while</span> injecting object [org.example.DemoComponent@5fe7cb6] of type [org.example.DemoComponent]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.example.BaseTestParallelInjection.lambda$runInjection$2(BaseTestParallelInjection.java:60)
	... 73 more
Caused by: java.lang.RuntimeException: error <span class="code-keyword">while</span> injecting object [org.example.DemoComponent@5fe7cb6] of type [org.example.DemoComponent]
	at org.apache.wicket.injection.Injector.inject(Injector.java:122)
	at org.apache.wicket.spring.injection.annot.SpringComponentInjector.inject(SpringComponentInjector.java:124)
	at org.example.BaseTestParallelInjection.lambda$runInjection$0(BaseTestParallelInjection.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:833)
Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:170)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at org.apache.wicket.proxy.bytebuddy.ByteBuddyProxyFactory.createOrGetProxyClass(ByteBuddyProxyFactory.java:105)
	at org.apache.wicket.proxy.bytebuddy.ByteBuddyProxyFactory.createProxy(ByteBuddyProxyFactory.java:75)
	at org.apache.wicket.proxy.LazyInitProxyFactory.createProxy(LazyInitProxyFactory.java:160)
	at org.apache.wicket.spring.injection.annot.AnnotProxyFieldValueFactory.getFieldValue(AnnotProxyFieldValueFactory.java:166)
	at org.apache.wicket.injection.Injector.inject(Injector.java:111)
	... 6 more
Caused by: java.lang.IllegalStateException: Cannot inject already loaded type: <span class="code-keyword">class </span>org.example.beans.WicketProxy_ServiceA
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:286)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:241)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:148)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6317)
	at org.apache.wicket.proxy.bytebuddy.ByteBuddyProxyFactory.lambda$createOrGetProxyClass$0(ByteBuddyProxyFactory.java:119)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	... 12 more

</pre>
</div></div>


<p>I'll try to debug later this week (don't have much free time <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/>(( )</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p>Adding</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>3.0.0-M9</version>
</plugin> </pre>
</div></div>
<p>helped to run the tests with Maven and it reproduces the problem!</p>

<p>I will try to debug it soon!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
diff --git wicket-ioc/src/main/java/org/apache/wicket/proxy/bytebuddy/ByteBuddyProxyFactory.java wicket-ioc/src/main/java/org/apache/wicket/proxy/bytebuddy/ByteBuddyProxyFactory.java
index 4d53be283b..1757a6bde8 100644
--- wicket-ioc/src/main/java/org/apache/wicket/proxy/bytebuddy/ByteBuddyProxyFactory.java
+++ wicket-ioc/src/main/java/org/apache/wicket/proxy/bytebuddy/ByteBuddyProxyFactory.java
@@ -116,7 +116,7 @@ <span class="code-keyword">public</span> <span class="code-keyword">class </span>ByteBuddyProxyFactory <span class="code-keyword">implements</span> IProxyFactory
                                                .implement(InterceptorMutator.class).intercept(FieldAccessor.ofBeanProperty())
                                                .implement(Serializable.class, IWriteReplace.class, ILazyInitProxy.class).intercept(MethodDelegation.toField(INTERCEPTOR_FIELD_NAME))
                                                .make()
-                                               .load(classLoader, ClassLoadingStrategy.Default.INJECTION)
+                                               .load(classLoader)
                                                .getLoaded());
 </pre>
</div></div>
<p>this fixes the problem. Using ClassLoadingStrategy.Default.WRAPPER also works.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphw" class="user-hover" rel="raphw">raphw</a> If you have a second to review this change we would greatly thankful!</p>

<p>The ByteBuddy related code in Wicket is at <a href="https://github.com/apache/wicket/blob/4affb7b18424e40663239ac9c93d9ec33a432541/wicket-ioc/src/main/java/org/apache/wicket/proxy/bytebuddy/ByteBuddyProxyFactory.java#L105-L120" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/wicket/blob/4affb7b18424e40663239ac9c93d9ec33a432541/wicket-ioc/src/main/java/org/apache/wicket/proxy/bytebuddy/ByteBuddyProxyFactory.java#L105-L120</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=solomax">solomax</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov" class="user-hover" rel="mgrigorov">mgrigorov</a> just tested with <blockquote><p>.load(classLoader)</p></blockquote> both wicket tests and attached project are green <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphw">raphw</a>:</i>
<p>The error message indicates that a class by the same name is already loaded. The load method accepts a class loading strategy as its second argument and it can be configured to ignore duplicates.</p>

<p>I do not really see how this can be related to package privateness.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphw" class="user-hover" rel="raphw">raphw</a> The issue is not about package privateness.  I am not sure why you got this impression.</p>

<p>The issue is that when using <br/>
.load(classLoader, ClassLoadingStrategy.Default.INJECTION)<br/>
ByteBuddy complains that it cannot load an interface class because it is already loaded. This happens only if there is a second attempt from a different thread.</p>

<p>There is no problem if just one thread uses ByteBuddy to create the proxy class.</p>

<p> </p>

<p>When using</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
.load(classLoader) </pre>
</div></div>
<p>or</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
.load(classLoader, ClassLoadingStrategy.Default.WRAPPER) </pre>
</div></div>
<p>there is no such issue.</p>

<p>I see nothing in the javadoc of INJECTION that explains this behavior.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphw">raphw</a>:</i>
<p>If you have an inherent strategy that a class with the same name does represent the same class, you can use this switch: <a href="https://javadoc.io/static/net.bytebuddy/byte-buddy/1.7.10/net/bytebuddy/dynamic/loading/ClassLoadingStrategy.Default.html#allowExistingTypes--" class="external-link" target="_blank" rel="nofollow noopener">https://javadoc.io/static/net.bytebuddy/byte-buddy/1.7.10/net/bytebuddy/dynamic/loading/ClassLoadingStrategy.Default.html#allowExistingTypes--</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p>Thanks for the hint!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit ad4d6313ad60bd32ba068a25557a0c280e43b085 in wicket's branch refs/heads/wicket-9.x from Martin Tzvetanov Grigorov<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=ad4d6313ad" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=ad4d6313ad</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7005" title="ByteBuddy IllegalStateException: Cannot inject already loaded type" class="issue-link" data-issue-key="WICKET-7005"><del>WICKET-7005</del></a>: ByteBuddy IllegalStateException: Cannot inject already loaded type</p>

<p>Configure ByteBuddy to not fail on already loaded classes</p>

<p>Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 12a803c96e32cf82fb3acfe2928beaea5ef0c407 in wicket's branch refs/heads/master from Martin Tzvetanov Grigorov<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=12a803c96e" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=12a803c96e</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7005" title="ByteBuddy IllegalStateException: Cannot inject already loaded type" class="issue-link" data-issue-key="WICKET-7005"><del>WICKET-7005</del></a>: ByteBuddy IllegalStateException: Cannot inject already loaded type</p>

<p>Configure ByteBuddy to not fail on already loaded classes</p>

<p>Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 5d46ca58cc835b2ac925c14190260c6253db2c3e in wicket's branch refs/heads/master from Martin Tzvetanov Grigorov<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=5d46ca58cc" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=5d46ca58cc</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7005" title="ByteBuddy IllegalStateException: Cannot inject already loaded type" class="issue-link" data-issue-key="WICKET-7005"><del>WICKET-7005</del></a>: Update the cherry-picked commit to jakarta.**</p>

<p>Update Spring to 6.0.5 and jakarta.servlet-api to 6.0.0 (Spring requires<br/>
this version).<br/>
Remove Servlet APIs which were deprecated in 5.0.0 and removed in 6.0.0</p>

<p>Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 75e51f77cc0f6a9b333853cd756ce9a272f16507 in wicket's branch refs/heads/master from Martin Tzvetanov Grigorov<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=75e51f77cc" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=75e51f77cc</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7005" title="ByteBuddy IllegalStateException: Cannot inject already loaded type" class="issue-link" data-issue-key="WICKET-7005"><del>WICKET-7005</del></a>: Cookie comments are not supported in Servlet 6.x</p>

<p>Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>:</i>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
If you have an inherent strategy that a <span class="code-keyword">class </span>with the same name does represent the same class, you can use <span class="code-keyword">this</span> <span class="code-keyword">switch</span>: https:<span class="code-comment">//javadoc.io/<span class="code-keyword">static</span>/net.bytebuddy/<span class="code-object">byte</span>-buddy/1.7.10/net/bytebuddy/dynamic/loading/ClassLoadingStrategy.Default.html#allowExistingTypes-- </span></pre>
</div></div>
<p>What if you dont? This seems to be a kind of race condition in Bytebuddy. If we set this swtich and have the same names for Springbeans this can still fail, right? The Unittest indicates that this is a race condition problem because it does not occur in single thread context.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphw">raphw</a>:</i>
<p>There's an overload: <a href="https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/TypeCache.java#L184" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/TypeCache.java#L184</a></p>

<p>Maybe you could provide the base type as a monitor, then the creation will be synchronized upon it. But if the probability for a collision is very low and there are many lookups, and if you can hold the mentioned condition, then ignoring collisions like described might be the more efficient option.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 4ed118cde785a0c53792603aae5951fb0561c641 in wicket's branch refs/heads/master from Martin Tzvetanov Grigorov<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=4ed118cde7" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=4ed118cde7</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7005" title="ByteBuddy IllegalStateException: Cannot inject already loaded type" class="issue-link" data-issue-key="WICKET-7005"><del>WICKET-7005</del></a>: Fix the broken Servlet APIs in wicket-native-websocket modules</p>

<p>Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth" class="user-hover" rel="renoth">renoth</a> Please open an issue at ByteBuddy Github repo if you think there is a bug or a room for improvement in it.</p>

<p>Or comment here if you think Wicket should be improved.</p>

<p>Thank you all!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>:</i>
<p>I think Wicket should not assume that every Wicket Application has Springbeans that do not have the same Classname (if that is what Bytebuddy uses as identifier for the cache) twice or more. Maybe it should be possible to give users the option to optionally enable Bytebuddy-Cache-Synchronization to avoid race conditions with the overloaded API mentioned by Rafael.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphw">raphw</a>:</i>
<p>I'd enable it by default. The cache makes an unsynchronized check first, so we are talking about atartup costs, and it's likely not a problem.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth" class="user-hover" rel="renoth">renoth</a> I don't understand your concern. An application can have exactly one Class with a given name per classloader. What do you mean with "spring beans which do not have the same classname" ?</p>

<p> </p>

<p>I also think there is a race condition in ByteBuddy due to the usage of ConcurrentMap#get() + check for null, e.g. here <a href="https://github.com/raphw/byte-buddy/blob/665a090c733c37339788cc5a1c441bd47fb77ef0/byte-buddy-dep/src/main/java/net/bytebuddy/TypeCache.java#L127-L128." class="external-link" target="_blank" rel="nofollow noopener">https://github.com/raphw/byte-buddy/blob/665a090c733c37339788cc5a1c441bd47fb77ef0/byte-buddy-dep/src/main/java/net/bytebuddy/TypeCache.java#L127-L128 </a></p>

<p>Probably it should use the #compute() methods instead.</p>

<p>But I don't see how a Wicket application can break due to this after the latest <a href="https://javadoc.io/static/net.bytebuddy/byte-buddy/1.7.10/net/bytebuddy/dynamic/loading/ClassLoadingStrategy.Default.html#allowExistingTypes--" class="external-link" target="_blank" rel="nofollow noopener">fix</a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>:</i>
<p>Ah yes you are correct, the name is the Classname with package, so that cannot be the same ever, i was assuming only the simple name of the Class would be used as key.</p>

<p>See <a href="https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/TypeCache.java#L455" class="external-link" target="_blank" rel="nofollow noopener">TypeCache#455</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renoth">renoth</a>:</i>
<p>Thanks for fixing, when can we expect a Wicket 9.13 release?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=damien.hollis">damien.hollis</a>:</i>
<p>Thanks for fixing this!</p>
