### ISSUE TITLE
[WICKET-7081] Open packages to expose resources to other modules 

### ISSUE THREAD

**Issue by jira-importer** [jira-importer/jira-to-github-issues#89]
<p>JPMS encapsulates package resources making impossible for other modules to access them without explicitly opening their packages. The quickstart shows the problem with a simple page with a form used in a JPMS Java project.  Running 'mvn test' we get the following exception:</p>

<p> </p>
<blockquote><p><tt>Caused by: java.util.MissingResourceException: Unable to find property: 'Form.CSS.hidden-fields' for component: form <span class="error">&#91;class=org.apache.wicket.markup.html.form.Form&#93;</span>. Locale: null, style: null</tt><br/>
<tt>    at org.apache.wicket.core/org.apache.wicket.Localizer.getString(Localizer.java:268)</tt><br/>
<tt>    at org.apache.wicket.core/org.apache.wicket.Localizer.getString(Localizer.java:201)</tt><br/>
<tt>    at org.apache.wicket.core/org.apache.wicket.Localizer.getString(Localizer.java:131)</tt><br/>
<tt>    at org.apache.wicket.core/org.apache.wicket.Component.getString(Component.java:1847)</tt><br/>
<tt>    at org.apache.wicket.core/org.apache.wicket.Component.getString(Component.java:1834)</tt></p></blockquote>
<p> </p>

<p>our applications can't read property 'Form.CSS.hidden-fields=hidden-fields' from wicket-core bundle org.apache.wicket.Application.utf8.properties.</p>

<p>Hence we should check packages from different modules (wicket-core, wicket-extentions, etc...) to open those containing resources that must be exposed to all other modules.</p>

---
<details><summary><i>Originally reported by <a title="Andrea Del Bene" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bitstorm">bitstorm</a>, imported from: <a href="https://issues.apache.org/jira/browse/WICKET-7081" target="_blank">Open packages to expose resources to other modules </a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Trivial
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2023-10-20T11:57:11+00:00
<li><b>imported</b>: 2025-11-27
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit f913eae90776d2d546182899ed5ca1b1df97205c in wicket's branch refs/heads/master from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=f913eae907" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=f913eae907</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> added packages to open</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 6b639d4f8763b7dd4dff8b8e0b8675a840060aa6 in wicket's branch refs/heads/master from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=6b639d4f87" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=6b639d4f87</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> separate commit for the new module</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 117b6b789789677f6c65400ba328cd0edcf543ff in wicket's branch refs/heads/wicket-9.x from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=117b6b7897" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=117b6b7897</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> added packages to open</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 5f2d3daaf0aded4e55076a62cd4dbb4880967f23 in wicket's branch refs/heads/master from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=5f2d3daaf0" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=5f2d3daaf0</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> opened packages for wicket-devutils</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 9bf07150f32376600b7194398e015aabc5d40e5b in wicket's branch refs/heads/wicket-9.x from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=9bf07150f3" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=9bf07150f3</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> opened packages for wicket-devutils</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit de49d03d329d655a9e38687d8b4cb924f717892d in wicket's branch refs/heads/wicket-9.x from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=de49d03d32" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=de49d03d32</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> opened packages for wicket-auth-roles</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit d7412524ede32c550ec8cfd68470dbfc93960839 in wicket's branch refs/heads/master from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=d7412524ed" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=d7412524ed</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> opened packages for wicket-native-websocket-core</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 680d50ad4092a4c1de4446565da67d96e15d6995 in wicket's branch refs/heads/wicket-9.x from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=680d50ad40" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=680d50ad40</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> opened packages for wicket-native-websocket-core</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 117b6b789789677f6c65400ba328cd0edcf543ff in wicket's branch refs/heads/reiern70/<a href="https://issues.apache.org/jira/browse/WICKET-7080" title="[Events] make default events delivery machinery pluggable and roll usable annotation based one" class="issue-link" data-issue-key="WICKET-7080"><del>WICKET-7080</del></a> from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=117b6b7897" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=117b6b7897</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> added packages to open</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 9bf07150f32376600b7194398e015aabc5d40e5b in wicket's branch refs/heads/reiern70/<a href="https://issues.apache.org/jira/browse/WICKET-7080" title="[Events] make default events delivery machinery pluggable and roll usable annotation based one" class="issue-link" data-issue-key="WICKET-7080"><del>WICKET-7080</del></a> from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=9bf07150f3" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=9bf07150f3</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> opened packages for wicket-devutils</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit de49d03d329d655a9e38687d8b4cb924f717892d in wicket's branch refs/heads/reiern70/<a href="https://issues.apache.org/jira/browse/WICKET-7080" title="[Events] make default events delivery machinery pluggable and roll usable annotation based one" class="issue-link" data-issue-key="WICKET-7080"><del>WICKET-7080</del></a> from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=de49d03d32" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=de49d03d32</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> opened packages for wicket-auth-roles</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jira-bot">jira-bot</a>:</i>
<p>Commit 680d50ad4092a4c1de4446565da67d96e15d6995 in wicket's branch refs/heads/reiern70/<a href="https://issues.apache.org/jira/browse/WICKET-7080" title="[Events] make default events delivery machinery pluggable and roll usable annotation based one" class="issue-link" data-issue-key="WICKET-7080"><del>WICKET-7080</del></a> from Andrea Del Bene<br/>
[ <a href="https://gitbox.apache.org/repos/asf?p=wicket.git;h=680d50ad40" class="external-link" target="_blank" rel="nofollow noopener">https://gitbox.apache.org/repos/asf?p=wicket.git;h=680d50ad40</a> ]</p>

<p><a href="https://issues.apache.org/jira/browse/WICKET-7081" title="Open packages to expose resources to other modules " class="issue-link" data-issue-key="WICKET-7081"><del>WICKET-7081</del></a> opened packages for wicket-native-websocket-core</p>
