### ISSUE TITLE
[WICKET-7071] Problems when calling request.getInputStream() before executing WicketFilter

### ISSUE THREAD

**Issue by jira-importer** [jira-importer/jira-to-github-issues#99]
<p>Calling request.getInputStream() (without reading any data from the stream), followed by a WicketFilter, causes certain wicket requests to fail.</p>

<p>If no call to request.getInputStream() is made, everything works as expected.</p>

<p>See runnable, minimal Maven project here: <a href="https://github.com/gluser1357/jerseyissues/tree/issue-4867-wicket10" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/gluser1357/jerseyissues/tree/issue-4867-wicket10</a> > readme.txt.</p>

<p>The issue is always reproducable e. g. in Jetty 11 and Tomcat 10.1.x (Jakarta Servlet 5+).</p>

<p>A use case for the described filter combination is e. g. to add an existing Jersey-based authorization filter in front of a Wicket application. Since Jersey calls at some point request.getInputStream(), our Wicket application fails at then. See more details on this here: <a href="https://github.com/eclipse-ee4j/jersey/issues/4867" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/eclipse-ee4j/jersey/issues/4867</a><br/>
 <br/>
 </p>

---
<details><summary><i>Originally reported by <a title="Sam Peters" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gluser1357">gluser1357</a>, imported from: <a href="https://issues.apache.org/jira/browse/WICKET-7071" target="_blank">Problems when calling request.getInputStream() before executing WicketFilter</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Bug
<li><b>resolved</b>: 2023-09-13T19:11:18+00:00
<li><b>imported</b>: 2025-11-27
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p><a href="https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getInputStream()" class="external-link" target="_blank" rel="nofollow noopener">https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getInputStream()</a> says: "Either this method or <a href="https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getReader()" class="external-link" target="_blank" rel="nofollow noopener"><tt>getReader()</tt></a> may be called to read the body, not both. "</p>

<p> </p>

<p>Does your application use Wicket CSP (content security policy) ?</p>

<p>./wicket-core/src/main/java/org/apache/wicket/csp/ReportCSPViolationMapper.java:85:                        if (-1 != (n = httpRequest.getReader().read(buffer)))</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER302119">JIRAUSER302119</a>:</i>
<p>Thank you for your fast response! I'm not aware of using CSP, see the linked runnable example (the link was incorrect but works now). If the code line above would run after getInputStream() has been called it would likely fail with "<tt>java.lang.IllegalStateException: getInputStream() has already been called for this request</tt>".</p>

<p>Some more potential findings:</p>
<ul>
	<li><a href="https://stackoverflow.com/questions/53602262/is-it-ok-to-call-servletrequest-getinputstream-multiple-times-in-loop," class="external-link" target="_blank" rel="nofollow noopener">https://stackoverflow.com/questions/53602262/is-it-ok-to-call-servletrequest-getinputstream-multiple-times-in-loop</a> says: "getInputStream() may be called multiple times."</li>
	<li><a href="https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getParameter(java.lang.String)" class="external-link" target="_blank" rel="nofollow noopener">https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getParameter(java.lang.String)</a> says: "If the parameter data was sent in the request body, such as occurs with an HTTP POST request, then reading the body directly via <a href="https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getInputStream()" class="external-link" target="_blank" rel="nofollow noopener"><tt>getInputStream()</tt></a> or <a href="https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getReader()" class="external-link" target="_blank" rel="nofollow noopener"><tt>getReader()</tt></a> can interfere with the execution of this method.".</li>
	<li><a href="https://stackoverflow.com/questions/8522568/why-is-httpservletrequest-inputstream-empty," class="external-link" target="_blank" rel="nofollow noopener">https://stackoverflow.com/questions/8522568/why-is-httpservletrequest-inputstream-empty</a> says: "It will be empty if it's already consumed beforehand. This will be implicitly done whenever you call <tt>getParameter()</tt>, <tt>getParameterValues()</tt>, <tt>getParameterMap()</tt>, <tt>getReader()</tt>, etc on the <tt>HttpServletRequest</tt>. Make sure that you don't call any of those kind of methods which by themselves need to gather information from the request body before calling <tt>getInputStream()</tt>."</li>
	<li><a href="https://github.com/spring-projects/spring-boot/issues/5676" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/spring-projects/spring-boot/issues/5676</a> says "...the input stream will only be empty if it was a <tt>POST</tt> request with a content type of <tt>multipart/form-data</tt> or <tt>application/x-www-form-url-encoded</tt>. In those cases, the request's body is then available via <tt>getParameters()</tt> or <tt>getParts()</tt> so there's typically no need to use the input stream." (referres likely to <a href="https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html)" class="external-link" target="_blank" rel="nofollow noopener">https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html)</a></li>
</ul>


<p>But even with that all in mind I see no obvious reason why a simple initial getInputStream() would make a difference.</p>

<p>Do you see anything special of the POST request in the example and its handling by Wicket code?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<blockquote><p>see the linked runnable example</p></blockquote>
<p>Unfortunately the linked example is not created by the Wicket Quickstart (<a href="https://wicket.apache.org/start/quickstart.html)." class="external-link" target="_blank" rel="nofollow noopener">https://wicket.apache.org/start/quickstart.html).</a> We recommend the quickstart because it makes it easier to debug the application.</p>

<p> </p>
<blockquote><p> "<tt>java.lang.IllegalStateException: getInputStream() has already been called for this request</tt>".</p></blockquote>
<p>Please paste the exception stack trace. It would make it clear why/where it breaks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER302119">JIRAUSER302119</a>:</i>
<p>> We recommend the quickstart because it makes it easier to debug the application.</p>

<p>Ok, here is the quickstart version to demonstrate the issue: <a href="https://github.com/gluser1357/jerseyissues/tree/wicket-issue-7071-quickstart" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/gluser1357/jerseyissues/tree/wicket-issue-7071-quickstart</a>. Since Start.java had initially compile errors I had to remove the unneeded SslContextFactory code block to get it running.</p>

<p> </p>

<p>> Please paste the exception stack trace. It would make it clear why/where it breaks.</p>

<p>I'm not sure how to create a CSP violation to trigger the code in ReportCSPViolationMapper.java:85. If I know how I could add that into my code example. In the case that getReader() would be directly called after getInputStream() (see FirstFilter.java in my code example) I get an exception (as expected). In Jetty:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.IllegalStateException: STREAMED
	at org.eclipse.jetty.server.Request.getReader(Request.java:1153)
	at gluser1357.FirstFilter.doFilter(FirstFilter.java:28)
	at jakarta.servlet.http.HttpFilter.doFilter(HttpFilter.java:97)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
...</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<blockquote><p>java.lang.IllegalStateException: STREAMED<br/>
	at org.eclipse.jetty.server.Request.getReader(Request.java:1153)<br/>
	at gluser1357.FirstFilter.doFilter(FirstFilter.java:28)<br/>
	at jakarta.servlet.http.HttpFilter.doFilter(HttpFilter.java:97)</p></blockquote>
<p>This shows that the problem is in your code. As I said in my first comment an application cannot use both .getInputStream() and .getReader() in the same request. You should remove the usage of getReader() at <br/>
gluser1357.FirstFilter.doFilter(FirstFilter.java:28)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER302119">JIRAUSER302119</a>:</i>
<p>> This shows that the problem is in your code. </p>

<p>No, it isn't: I added some test lines today in FirstFilter.doFilter() to call getReader(), just to demonstrate you the stacktrace that would likely be similar to the one created in ReportCSPViolationMapper.java:85 in case of a CSP violation (as I said, I currently don't know how to provoke such a violation and I'm quite sure that the initial issue <a href="https://issues.apache.org/jira/browse/WICKET-7071" title="Problems when calling request.getInputStream() before executing WicketFilter" class="issue-link" data-issue-key="WICKET-7071"><del>WICKET-7071</del></a> has nothing to do with CSP violations at all). In the normal case (according to my quickstart), getReader() would NEVER be called in our project.</p>

<p>Could you please run the supplied quickstart and look if you can reproduce the issue according to the steps of the readme.txt in my project?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p>Debugged the problem with embedded Jetty.</p>

<p>It appears that jakarta.servlet.ServletRequest#getParameterMap() would read the parameters only if there was no call to jakarta.servlet.ServletRequest#getInputStream and/or jakarta.servlet.ServletRequest#getReader()</p>

<p> </p>

<p><span class="image-wrap" style=""><img src="https://issues.apache.org/jira/secure/attachment/13062750/13062750_wicket-7071-first-getInputStream.png" style="border: 0px solid black" /></span></p>

<p>Above you can see that Request._inputState changes from 0 (initial) to 1 (inputStream).</p>

<p> </p>

<p><span class="image-wrap" style=""><img src="https://issues.apache.org/jira/secure/attachment/13062751/13062751_wicket-7071-getParameters.png" style="border: 0px solid black" /></span></p>

<p>And here you can see that when Wicket calls #getParameterMap() would populate the Map only if the Request state is 0 (initial), but does nothing for 1 (inputStream) and 2 (reader).</p>

<p> </p>

<p><a href="https://jakarta.ee/specifications/servlet/6.0/jakarta-servlet-spec-6.0#when-parameters-are-available" class="external-link" target="_blank" rel="nofollow noopener">https://jakarta.ee/specifications/servlet/6.0/jakarta-servlet-spec-6.0#when-parameters-are-available</a> does not explain why it behaves like that. You may want to check with the Jetty (or Tomcat) team for more information.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER302119">JIRAUSER302119</a>:</i>
<p>Thank you for debugging! I added some debugging on the quickstart, see update in <a href="https://github.com/gluser1357/jerseyissues/tree/wicket-issue-7071-quickstart" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/gluser1357/jerseyissues/tree/wicket-issue-7071-quickstart</a>. When I run Start.java, press the link with getInputStream(), followed by the the link without, I get the output below. Its obvious that all form parameters retrieved by getParameterMap() are missing if getInputStream() has been called before (query parameters are not affected). I agree that the spec does not explain this behaviour.</p>

<p>Workarounds would be to a) not calling getInputStream() in all preceeding filters before WicketFilter starts (in my case it's Jersey wo does that even if no data is read), or b) make Wicket check if getInputStream() has data, and if it's the case, read and parse the form params from the stream instead using the Servlet getParameter() API. But, the cleanest solution for me would be, as you said, to fix this issue in Jetty and Tomcat, or at least say something about this behaviour in the Servlet docs you mentioned. If I find the time I'll try to open appropriate tickets.</p>

<p>=== OUTPUT ===<br/>
<font color="#172b4d"><span class="error">&#91;qtp94345706-21&#93;</span> INFO gluser1357.FirstFilter - </font></p>

<p><font color="#172b4d"><span class="error">&#91;qtp94345706-21&#93;</span> INFO gluser1357.FirstFilter - QueryString: 0-1.0-mainMenu-form-rowPanel-addRowWith</font></p>

<p><font color="#172b4d"><span class="error">&#91;qtp94345706-21&#93;</span> INFO gluser1357.FirstFilter - Content-Type: application/x-www-form-urlencoded; charset=UTF-8</font></p>

<p><font color="#172b4d"><span class="error">&#91;qtp94345706-21&#93;</span> INFO gluser1357.FirstFilter - Content-Length: 55</font></p>

<p><font color="#172b4d"><span class="error">&#91;qtp94345706-21&#93;</span> INFO gluser1357.FirstFilter - Call getInputStream()</font></p>

<p><font color="#172b4d"><span class="error">&#91;qtp94345706-21&#93;</span> INFO gluser1357.FirstFilter - Call getParameterMap()</font></p>

<p><font color="#00875a"><span class="error">&#91;qtp94345706-21&#93;</span> INFO gluser1357.FirstFilter - Parameter count: 1</font></p>

<p><font color="#00875a"><span class="error">&#91;qtp94345706-21&#93;</span> INFO gluser1357.FirstFilter - 0-1.0-mainMenu-form-rowPanel-addRowWith=[Ljava.lang.String;@fed9457</font></p>

<p><font color="#172b4d"><span class="error">&#91;qtp94345706-22&#93;</span> INFO gluser1357.FirstFilter - </font></p>

<p><font color="#172b4d"><span class="error">&#91;qtp94345706-22&#93;</span> INFO gluser1357.FirstFilter - QueryString: 0-1.0-mainMenu-form-rowPanel-addRow____</font></p>

<p><font color="#172b4d"><span class="error">&#91;qtp94345706-22&#93;</span> INFO gluser1357.FirstFilter - Content-Type: application/x-www-form-urlencoded; charset=UTF-8</font></p>

<p><font color="#172b4d"><span class="error">&#91;qtp94345706-22&#93;</span> INFO gluser1357.FirstFilter - Content-Length: 55</font></p>

<p><font color="#172b4d"><span class="error">&#91;qtp94345706-22&#93;</span> INFO gluser1357.FirstFilter - Call getParameterMap()</font></p>

<p><font color="#ff0000"><span class="error">&#91;qtp94345706-22&#93;</span> INFO gluser1357.FirstFilter - Parameter count: 3</font></p>

<p><font color="#ff0000"><span class="error">&#91;qtp94345706-22&#93;</span> INFO gluser1357.FirstFilter - 0-1.0-mainMenu-form-rowPanel-addRow____=[Ljava.lang.String;@439c0485</font></p>

<p><font color="#ff0000"><span class="error">&#91;qtp94345706-22&#93;</span> INFO gluser1357.FirstFilter - rowPanel:rows:0:text=[Ljava.lang.String;@349efca6</font></p>

<p><font color="#ff0000"><span class="error">&#91;qtp94345706-22&#93;</span> INFO gluser1357.FirstFilter - rowPanel:addRow____=[Ljava.lang.String;@653a62ef</font></p>

<p> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p>You can work around your issue by using a Servlet request wrapper that returns a wrapper of the input stream and calls the Jetty/Tomcat one only when one of its methods is called.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER302119">JIRAUSER302119</a>:</i>
<p>Thank you. I am aware of such wrapping workarounds but they may have their own drawbacks in the common case (redundant writing and testing required, problems with large data buffering, ...).</p>

<p>Today, one alternative workaround came to my mind which does not require additional wrapping. The idea is to simply call getParameterMap() before any other filters come into play:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> <span class="code-keyword">class </span>ReadParamsIfFormEncodedFilter <span class="code-keyword">extends</span> HttpFilter {
 
    @Override
    <span class="code-keyword">public</span> void doFilter(HttpServletRequest request, HttpServletResponse response, FilterChain chain) <span class="code-keyword">throws</span> IOException, ServletException {
 
<span class="code-keyword">if</span> (<span class="code-quote">"post"</span>.equals(request.getMethod().toLowerCase()) &&
    request.getContentType() != <span class="code-keyword">null</span> &&
    request.getContentType().toLowerCase().contains(<span class="code-quote">"application/x-www-form-urlencoded"</span>)) {
    request.getParameterMap();
}
chain.doFilter(request, response);
    }
}
</pre>
</div></div>
<p>Of course, we don't know if and how subsequent filters or servlets, like Jersey, will extract form parameters exactly - from input stream or via getParameter* API. So it's just another workaround but for the issue here it seems to work as expected. I commited the filter in my example project linked above (the filter must be included in web.xml, it's still commented out there).</p>
